- hosts: localhost
  gather_facts: false
  tasks:
    # PyVmomi is required for everything
    # aiohttp was temp required for testing - might be able to remove? 2/7/22
    # now I'm adding "setuptools" from: https://github.com/vmware/vsphere-automation-sdk-python
    - name: Ensure Python is configured with proper modules for vmware community usage
      ansible.builtin.pip:
        name:
          - PyVmomi
          - aiohttp
          - setuptools
          - git+https://github.com/vmware/vsphere-automation-sdk-python.git

    - name: Configure NTP servers on esxi
      community.vmware.vmware_host_ntp:
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        hostname: "{{ hostvars[item].ansible_host }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        validate_certs: false
        state: present
        ntp_servers: "{{ esxi.ntp_servers }}"
      loop: "{{ groups['esxi'] }}"
      run_once: true # no need to do for each host
      delegate_to: localhost

    - name: Start and enable NTP service
      community.vmware.vmware_host_service_manager:
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        hostname: "{{ hostvars[item].ansible_host }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        validate_certs: false
        service_name: ntpd
        state: present
        service_policy: on
      loop: "{{ groups['esxi'] }}"
      run_once: true # no need to do for each host
      delegate_to: localhost

    - name: Create Datacenter - '{{ vcenter.datacenter }}'
      community.vmware.vmware_datacenter:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        state: present
        validate_certs: false

    - name: Create Cluster - '{{ vcenter.cluster }}'
      community.vmware.vmware_cluster:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        cluster_name: "{{ vcenter.cluster }}"
        validate_certs: false

    - name: Add ESXi Host(s) to vCenter
      community.vmware.vmware_host:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        datacenter: "{{ vcenter.datacenter }}"
        cluster: "{{ vcenter.cluster }}"
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        esxi_username: "{{ esxi.username }}"
        esxi_password: "{{ esxi.password }}"
        state: add_or_reconnect
        validate_certs: false
      loop: "{{ groups['clusterhosts'] }}"

    - name: Enable EVC Mode '{{ esxi.evc_mode }}'
      community.vmware.vmware_evc_mode:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datacenter_name: "{{ vcenter.datacenter }}"
        cluster_name: "{{ vcenter.cluster }}"
        evc_mode: "{{ esxi.evc_mode }}"
        state: present

    - name: Add vCenter Host to vCenter
      community.vmware.vmware_host:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        datacenter: "{{ vcenter.datacenter }}"
        folder: "/{{ vcenter.datacenter }}/host"
        esxi_hostname: "{{ vcenter.host }}"
        esxi_username: "{{ esxi.username }}"
        esxi_password: "{{ esxi.password }}"
        state: present
        validate_certs: false

    - name: Set NTP servers for all ESXi Hosts in '{{ vcenter.cluster }}' cluster
      community.vmware.vmware_host_ntp:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        cluster_name: "{{ vcenter.cluster }}"
        state: present
        ntp_servers: "{{ esxi.ntp_servers }}" 

    - name: Disable IPv6 for all ESXi Hosts in '{{ vcenter.cluster }}' cluster
      community.vmware.vmware_host_ipv6:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        cluster_name: "{{ vcenter.cluster }}"
        state: disabled

    - name: Add a new vCenter license
      community.vmware.vcenter_license:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        license: "{{ vcenter.license }}"
        state: present

    - name: Add ESXi license and assign to the ESXi host
      community.vmware.vcenter_license:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        license: "{{ esxi.license }}"
        state: present
      loop: "{{ groups['esxi'] }}"

    - name: Enable vSphere HA with admission control for '{{ vcenter.cluster }}'
      community.vmware.vmware_cluster_ha:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datacenter_name: "{{ vcenter.datacenter }}"
        cluster_name: "{{ vcenter.cluster }}"
        ha_vm_monitoring: vmMonitoringOnly
        # vs. shutdown or none
        host_isolation_response: "powerOff"
        reservation_based_admission_control:
          failover_level: 1
        advanced_settings:
          "das.ignoreRedundantNetWarning": "true"
          "das.ignoreInsufficientHbDatastore": "true"
        enable: true

    - name: Enable DRS for '{{ vcenter.cluster }}'
      community.vmware.vmware_cluster_drs:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datacenter_name: "{{ vcenter.datacenter }}"
        cluster_name: "{{ vcenter.cluster }}"
        enable: true

    - name: Add resource pool named '{{ resource_pool_name }}' to vCenter
      community.vmware.vmware_resource_pool:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datacenter: "{{ vcenter.datacenter }}"
        cluster: "{{ vcenter.cluster }}"
        resource_pool: "{{ resource_pool_name }}"
        mem_shares: normal
        mem_limit: -1
        mem_reservation: 0
        mem_expandable_reservations: true
        cpu_shares: normal
        cpu_limit: -1
        cpu_reservation: 0
        cpu_expandable_reservations: true
        state: present
