
- hosts: localhost
  gather_facts: false
  tasks:

  # PyVmomi is required for everything
  # aiohttp was temp required for testing - might be able to remove? 2/7/22
  # now I'm adding "setuptools" from: https://github.com/vmware/vsphere-automation-sdk-python
  - name: Ensure Python is configured with proper modules for vmware community usage
    ansible.builtin.pip:
      name:
        - PyVmomi
        - aiohttp
        - setuptools
        - git+https://github.com/vmware/vsphere-automation-sdk-python.git

  - name: Create Datacenter - '{{ datacenter_name }}'
    community.vmware.vmware_datacenter:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      state: present
      validate_certs: false

  - name: Create Cluster - '{{ cluster_name }}'
    community.vmware.vmware_cluster:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      cluster_name: '{{ cluster_name }}'
      validate_certs: false

  - name: Enable EVC Mode '{{ evc_mode }}'
    community.vmware.vmware_evc_mode:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter_name: '{{ datacenter_name }}'
      cluster_name: '{{ cluster_name }}'
      evc_mode: '{{ evc_mode }}'
      state: present

  - name: Add ESXi Host(s) to vCenter
    community.vmware.vmware_host:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter_name }}'
      cluster: '{{ cluster_name }}'
      esxi_hostname: '{{ hostvars[item].ansible_host }}'
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ esxi_password }}'
      state: present
      validate_certs: false
    loop: "{{ groups['clusterhosts'] }}"

  - name: Set NTP servers for all ESXi Hosts in '{{ cluster_name }}' cluster
    community.vmware.vmware_host_ntp:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      cluster_name: '{{ cluster_name }}'
      state: present
      ntp_servers:
        - ntp11.metas.ch
        - ntp12.metas.ch
        - ntp13.metas.ch
        - 0.pool.ntp.org

  - name: Disable IPv6 for all ESXi Hosts in '{{ cluster_name }}' cluster
    community.vmware.vmware_host_ipv6:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      cluster_name: '{{ cluster_name }}'
      state: disabled

  - name: Add a new vCenter license
    community.vmware.vcenter_license:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      license: '{{ vcenter_license }}'
      state: present
  
  - name: Add ESXi license and assign to the ESXi host
    community.vmware.vcenter_license:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      esxi_hostname: '{{ hostvars[item].ansible_host }}'
      license: '{{ esxi_license }}'
      state: present
    loop: "{{ groups['esxi'] }}"

  - name: Enable vSphere HA with admission control for '{{ cluster_name }}'
    community.vmware.vmware_cluster_ha:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter_name: '{{ datacenter_name }}'
      cluster_name: '{{ cluster_name }}'
      ha_vm_monitoring: vmMonitoringOnly
      # vs. shutdown or none
      host_isolation_response: "powerOff"
      reservation_based_admission_control:
        failover_level: 1
      advanced_settings:
        'das.ignoreRedundantNetWarning': 'true'
        'das.ignoreInsufficientHbDatastore': 'true'
      enable: true

  - name: Enable DRS for '{{ cluster_name }}'
    community.vmware.vmware_cluster_drs:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter_name: '{{ datacenter_name }}'
      cluster_name: '{{ cluster_name }}'
      enable: true

  - name: Add resource pool named '{{ resource_pool_name }}' to vCenter
    community.vmware.vmware_resource_pool:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter: '{{ datacenter_name }}'
      cluster: '{{ cluster_name }}'
      resource_pool: '{{ resource_pool_name }}'
      mem_shares: normal
      mem_limit: -1
      mem_reservation: 0
      mem_expandable_reservations: true
      cpu_shares: normal
      cpu_limit: -1
      cpu_reservation: 0
      cpu_expandable_reservations: true
      state: present
