- hosts: localhost
  gather_facts: false
  tasks:

  # This is final state so I let it run no matter what.
  - name: Replace hosts physical nic with '{{ physical_nic_1 }}' on VDS '{{ ops_dvs_switch_name }}'
    community.vmware.vmware_dvs_host:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      esxi_hostname: '{{ hostvars[item].ansible_host }}'
      switch_name: '{{ ops_dvs_switch_name }}'
      vmnics:
          - '{{ physical_nic_1 }}'
      state: present
    loop: "{{ groups['clusterhosts'] }}"

  # This is final state so I let it run no matter what.
  - name: Add Hosts '{{ physical_nic_2 }}' to '{{ vm_dvs_switch_name }}'
    community.vmware.vmware_dvs_host:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      esxi_hostname: '{{ hostvars[item].ansible_host }}'
      switch_name: '{{ vm_dvs_switch_name }}'
      vmnics:
          - '{{ hostvars[item].physical_nic_2 }}'
      state: present
    loop: "{{ groups['clusterhosts'] }}"