- hosts: localhost
  gather_facts: false
  tasks:
    # ensure it's nfs or nfs4 - that is a tripping point.
    # I found NFS to be very finicky overall and would recommend if at all possible to use iSCSI instead.
    # I ran into issues like this: https://www.reddit.com/r/vmware/comments/dlc85v/nfs.datastore_appending_1_to_name_on_mountreboot/
    # until I switched to v3
    - name: Mounting NFS datastore '{{ nas.server_ip }}' to all ESXi hosts
      community.vmware.vmware_host_datastore:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datastore_name: "{{ nas.datastore_name }}"
        datastore_type: "{{ nas.datastore_type }}"
        nfs_server: "{{ nas.server_ip }}"
        nfs_path: "{{ nas.volume_path }}"
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        state: present
      loop: "{{ groups['esxi'] }}"

    - name: Enable iSCSI on all ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        state: enabled
      loop: "{{ groups['clusterhosts'] }}"

    - name: Add a dynamic target to iSCSI config on all ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        iscsi_config:
          vmhba_name: "{{ nas.vmhba_name }}"
          send_target:
            # iscsi_name: "{{ nas.iscsi_target }}"
            address: "{{ send_target_address }}"
        state: present
      loop: "{{ groups['clusterhosts'] }}"

    - name: Add VMKernels to iSCSI config on all ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        iscsi_config:
          vmhba_name: "{{ nas.vmhba_name }}"
          # must be a vmk
          port_bind:
            - "{{ vmk_storage }}"
        state: present
      loop: "{{ groups['clusterhosts'] }}"

    - name: Rescan datastores for a given cluster - all found hosts will be scanned
      community.vmware.vmware_host_scanhba:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        cluster_name: "{{ vcenter.cluster }}"
        validate_certs: false
        refresh_storage: true
