- hosts: localhost
  gather_facts: false
  tasks:
    # ensure it's nfs or nfs4 - that is a tripping point.
    # I found NFS to be very finicky overall and would recommend if at all possible to use iSCSI instead.
    # I ran into issues like this: https://www.reddit.com/r/vmware/comments/dlc85v/nfs.datastore_appending_1_to_name_on_mountreboot/
    # until I switched to v3
    - name: Mounting NFS datastore '{{ nas.server_ip }}' to all ESXi hosts
      community.vmware.vmware_host_datastore:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datastore_name: "{{ nas.nfs.datastore_name }}"
        datastore_type: "{{ nas.nfs.datastore_type }}"
        nfs_server: "{{ nas.server_ip }}"
        nfs_path: "{{ nas.nfs.volume_path }}"
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        state: present
      loop: "{{ groups['esxi'] }}"

    - name: Enable iSCSI on all ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        state: enabled
      loop: "{{ groups['clusterhosts'] }}"

    - name: Add a dynamic target to iSCSI config on all ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        iscsi_config:
          vmhba_name: "{{ nas.iscsi.vmhba_name }}"
          # send_target:
          static_target:
            iscsi_name: "{{ nas.iscsi.target }}"
            address: "{{ nas.server_ip }}"
        state: present
      loop: "{{ groups['clusterhosts'] }}"

    - name: Add VMKernels to iSCSI config on all ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
        iscsi_config:
          vmhba_name: "{{ nas.iscsi.vmhba_name }}"
          # must be a vmk
          port_bind:
            - "{{ vmk_storage }}"
        state: present
      loop: "{{ groups['clusterhosts'] }}"

    - name: Rescan datastores for a given cluster - all found hosts will be scanned
      community.vmware.vmware_host_scanhba:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        cluster_name: "{{ vcenter.cluster }}"
        validate_certs: false
        refresh_storage: true

    - name: Gather iSCSI configuration information of ESXi host
      community.vmware.vmware_host_disk_info:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ hostvars[item].ansible_host }}"
      delegate_to: localhost
      loop: "{{ groups['clusterhosts'] }}"
      register: iscsi_info

    - set_fact:
        iscsi_names: "{{ iscsi_info | json_query(query)}}"
      vars:
        query: "results[*].hosts_disk_info.*[?device_ctd_list[0] == `vmhba64:C0:T0:L1`].canonical_name"

    - name: Mount iSCSI datastore
      community.vmware.vmware_host_datastore:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        esxi_hostname: "{{ groups['esxi'][0][ansible_host] }}"
        datastore_name: "{{ nas.iscsi.datastore_name }}"
        datastore_type: "{{ nas.iscsi.datastore_type }}"
        vmfs_device_name: "{{ iscsi_names[0][0][0] }}"
        state: present
