# consider this to be specific to my use case and not worth cluttering the main modules.
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create local content library for OS images
      community.vmware.vmware_content_library_manager:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        library_name: os-images
        library_description: 'Library with OS images'
        library_type: local
        datastore_name: "{{ nas.nfs.datastore_name }}"
        state: present

    - name: Create a VM folders on datacenter  "{{ vcenter.datacenter }}"
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datacenter_name:  "{{ vcenter.datacenter }}"
        parent_folder: "{{ (item.split('/') | map('trim'))[:-1] | join('/') }}"
        folder_name: "{{ (item.split('/') | map('trim'))[-1:] | join('/') }}"
        folder_type: vm
        state: present
      loop: "{{ vm_folders }}"

    # - name: Create a VM folder for imported VMs on datacenter  "{{ vcenter.datacenter }}"
    #   community.vmware.vcenter_folder:
    #     hostname: "{{ vcenter.hostname }}"
    #     username: "{{ vcenter.username }}@{{ vcenter.domain }}"
    #     password: "{{ vcenter.sso_password }}"
    #     validate_certs: false
    #     datacenter_name:  "{{ vcenter.datacenter }}"
    #     folder_name: imported
    #     folder_type: vm
    #     state: present
    #   delegate_to: localhost
    #   run_once: true # no need to do for each host

    # - name: Register a template in cluster "{{ vcenter.cluster }}"
    #   community.vmware.vmware_guest_register_operation:
    #     hostname: "{{ vcenter.hostname }}"
    #     username: "{{ vcenter.username }}@{{ vcenter.domain }}"
    #     password: "{{ vcenter.sso_password }}"
    #     validate_certs: false
    #     datacenter:  "{{ vcenter.datacenter }}"
    #     folder: "/vm/templates"
    #     cluster: "{{ vcenter.cluster }}"
    #     name: "{{ vm_name }}"
    #     template: true
    #     path: "[NFS] templates/{{ vm_name }}/{{ vm_name }}.vmtx"
    #     state: present