# consider this to be specific to my use case and not worth cluttering the main modules.
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Local Content Library
      community.vmware.vmware_content_library_manager:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        library_name: os-images
        library_description: 'Library with OS images'
        library_type: local
        datastore_name: "{{ nas.nfs.datastore_name }}"
        state: present

    - name: Create a VM folder on given datacenter
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datacenter_name:  "{{ vcenter.datacenter }}"
        folder_name: templates
        folder_type: vm
        state: present
      register: vm_folder_creation_result

    - name: Register VM in Cluster
      community.vmware.vmware_guest_register_operation:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}@{{ vcenter.domain }}"
        password: "{{ vcenter.sso_password }}"
        validate_certs: false
        datacenter:  "{{ vcenter.datacenter }}"
        folder: "/vm/templates"
        cluster: "{{ vcenter.cluster }}"
        name: "{{ vm_name }}"
        template: true
        path: "[NFS] templates/{{ vm_name }}/{{ vm_name }}.vmtx"
        state: present