- hosts: localhost
  gather_facts: false
  tasks:

  - name: Delete Cluster - '{{ cluster_name }}'
    community.vmware.vmware_cluster:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      cluster_name: '{{ cluster_name }}'
      state: absent
      validate_certs: false

  - name: Delete Datacenter - '{{ datacenter_name }}'
    community.vmware.vmware_datacenter:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      state: absent
      validate_certs: false