- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register vCenter to inventory
      community.vmware.vmware_guest_register_operation:
        hostname: "{{ vcenter.host }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        folder: "/ha-datacenter/vm"
        esxi_hostname: "esx4.lab.tdeutsch.ch"
        name: "VMware vCenter Server"
        template: false
        path: "[NFS] VMware\ vCenter\ Server/VMware\ vCenter\ Server.vmx"
        state: present
        validate_certs: false
