- hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure VCSA is on
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter.host }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        validate_certs: false
        name: "VMware vCenter Server"
        state: powered-on

    - name: Wait for VCSA to be available
      uri:
        url: "{{ vcenter.server }}"
        return_content: yes
        validate_certs: false
      register: result
      until: "'on-prem-documentation-link' in result.content"
      retries: 20
      delay: 30

    - name: Wait for VCSA to be ready
      uri:
        url: "{{ vcenter.server }}/ui/"
        return_content: yes
        validate_certs: false
      register: result
      until: "'loading-container' in result.content"
      retries: 20
      delay: 30
