- hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure VCSA is off
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter.host }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        validate_certs: false
        name: "VMware vCenter Server"
        state: shutdown-guest
        state_change_timeout: 200
