---
all:
  hosts:
    esx1:
      ansible_host: 192.168.8.11
    esx2:
      ansible_host: 192.168.8.12
      physical_nic_2: "vmnic1"
    esx4:
      ansible_host: 192.168.8.14
    esx5:
      ansible_host: 192.168.8.15
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
  children:
    esxi:
      hosts:
        esx1: {}
        esx2: {}
        esx4: {}
        esx5: {}
      vars:
        # only required for limited direct SSH / Ansible modules generally for bootstraping hosts
        # without it, it runs but errors about the lack of python on esxi hosts
        ansible_python_interpreter: /bin/python
    clusterhosts:
      hosts:
        esx1: {}
        esx2: {}
        esx5: {}
      vars:
        # only required for limited direct SSH / Ansible modules generally for bootstraping hosts
        # without it, it runs but errors about the lack of python on esxi hosts
        ansible_python_interpreter: /bin/python
